version: '3.3'

services:
  db:
    image: mysql:8.0.22
    ports:
      - "33066:3306"
    restart: always
    environment:
      MYSQL_DATABASE: assessment
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: 'uPG-WY%a9Zg=L6BW'

  db_test:
    image: mysql:8.0.22
    ports:
      - "55055:3306"
    restart: always
    environment:
      MYSQL_DATABASE: assessment_test
      MYSQL_USER: user_test
      MYSQL_PASSWORD: password_test
      MYSQL_RANDOM_ROOT_PASSWORD: 'g72D!dsy@my#ZGdK'
