version: '3.3'

services:
  db:
    image: mysql:8.0.22
    ports:
      - "33066:3306"
    restart: always
    environment:
      MYSQL_DATABASE: assessment
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: 'uPG-WY%a9Zg=L6BW'
